### ISSUE TITLE
Hi, while rendering station sign the game crashed and I got this report:

### ISSUE THREAD

**Issue by Scwestbrook** [ChAoSUnItY/EkiLib#5]
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 12/18/20 8:52 AM
Description: Rendering Block Entity

java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_74] {}
	at com.chaos.eki_lib.tileentity.StationNameplateTileEntity.getStation(StationNameplateTileEntity.java:47) ~[?:1.0.17] {re:classloading}
	at com.chaos.eki_lib.tileentity.renderer.StationNameplateTER.render(StationNameplateTER.java:34) ~[?:1.0.17] {re:classloading,pl:runtimedistcleaner:A}
	at com.chaos.eki_lib.tileentity.renderer.StationNameplateTER.func_225616_a_(StationNameplateTER.java:19) ~[?:1.0.17] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:101) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$renderTileEntity$0(TileEntityRendererDispatcher.java:85) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:118) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:84) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1038) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:immersiveengineering:IE render hook after tile rendering,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4-forge-35.1.10.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.10.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_74] {}
	at com.chaos.eki_lib.tileentity.StationNameplateTileEntity.getStation(StationNameplateTileEntity.java:47) ~[?:1.0.17] {re:classloading}
	at com.chaos.eki_lib.tileentity.renderer.StationNameplateTER.render(StationNameplateTER.java:34) ~[?:1.0.17] {re:classloading,pl:runtimedistcleaner:A}
	at com.chaos.eki_lib.tileentity.renderer.StationNameplateTER.func_225616_a_(StationNameplateTER.java:19) ~[?:1.0.17] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:101) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$renderTileEntity$0(TileEntityRendererDispatcher.java:85) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Block Entity Details --
Details:
	Name: eki_lib:station_nameplate // com.chaos.eki_lib.tileentity.StationNameplateTileEntity
	Block: Block{eki_lib:station_nameplate}[facing=east]
	Block location: World: (-167,71,-10), Chunk: (at 9,4,6 in -11,-1; contains blocks -176,0,-16 to -161,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Block: Block{eki_lib:station_nameplate}[facing=east]
	Block location: World: (-167,71,-10), Chunk: (at 9,4,6 in -11,-1; contains blocks -176,0,-16 to -161,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:118) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:84) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1038) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:immersiveengineering:IE render hook after tile rendering,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['OttersMeep'/6, l='ClientLevel', x=-163.53, y=71.00, z=-9.68]]
	Chunk stats: Client Chunk Cache: 121, 49
	Level dimension: minecraft:overworld
	Level spawn location: World: (-167,72,-1), Chunk: (at 9,4,15 in -11,-1; contains blocks -176,0,-16 to -161,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 283173 game time, 51740 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4-forge-35.1.10.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.10.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Mac OS X (x86_64) version 10.15.7
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 571319000 bytes (544 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.10.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.10.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.10.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.10.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.10.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.10
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.10-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		Eki-2.0.1.jar                                     |Eki Mod                       |eki                           |2.0.1               |DONE      |NOSIGNATURE
		economyinc-1.6.9.4.jar                            |Economy Inc.                  |economyinc                    |1.6.8               |DONE      |NOSIGNATURE
		ImmersiveEngineering-1.16.4-4.1.1-128.jar         |Immersive Engineering         |immersiveengineering          |1.16.4-4.1.1-128    |DONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		movingelevators-1.2.29-mc1.16.4.jar               |Moving Elevators              |movingelevators               |1.2.29              |DONE      |NOSIGNATURE
		TrackAPI-1.16.4-forge-1.2.1.jar                   |TrackAPI                      |trackapi                      |1.2                 |DONE      |NOSIGNATURE
		mcw-windows-1.0.2-mc1.16.4.jar                    |Macaw's Windows               |mcwwindows                    |1.0.2               |DONE      |NOSIGNATURE
		car-1.16.4-1.0.5.jar                              |Ultimate Car Mod              |car                           |1.16.4-1.0.5        |DONE      |NOSIGNATURE
		rsgauges-1.16.3-1.2.5.jar                         |Gauges and Switches           |rsgauges                      |1.2.5               |DONE      |NOSIGNATURE
		AutoDropper-1.16.3-7.0.0.jar                      |Auto Dropper                  |autodropper                   |1.16.3-7.0.0        |DONE      |NOSIGNATURE
		extlights-3.1.jar                                 |Extended Lights               |extlights                     |3.1                 |DONE      |NOSIGNATURE
		[1.16.4]+SecurityCraft+v1.8.20.2.jar              |SecurityCraft                 |securitycraft                 |v1.8.20.2           |DONE      |NOSIGNATURE
		backpacked-1.7.0-mc1.16.3.jar                     |Backpacked                    |backpacked                    |1.7.0               |DONE      |NOSIGNATURE
		backpacker-1.1.0-mc1.16.3.jar                     |Backpacker                    |backpacker                    |1.1.0               |DONE      |NOSIGNATURE
		obfuscate-0.5.0-mc1.16.3.jar                      |Obfuscate                     |obfuscate                     |0.5.0               |DONE      |e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		vehicle-0.45.1-mc1.16.3.jar                       |MrCrayfish's Vehicle Mod      |vehicle                       |0.45.1              |DONE      |NOSIGNATURE
		neoncraft-2.1.jar                                 |Neon Craft                    |neoncraft                     |2.1                 |DONE      |NOSIGNATURE
		EkiLib-1.0.17.jar                                 |Eki Lib                       |eki_lib                       |1.0.17              |DONE      |NOSIGNATURE
		mcws-roofs-2.0.0-mc1.16.4.jar                     |Macaw's Roofs                 |mcwroofs                      |2.0.0               |DONE      |NOSIGNATURE
		cfm-7.0.0-pre19-mc1.16.3.jar                      |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre19         |DONE      |NOSIGNATURE
		mapperbase-1.16.4-2.3.0.0.jar                     |Mapper Base                   |mapperbase                    |1.16.4-2.3.0.0      |DONE      |NOSIGNATURE
		roadstuff-1.16.4-4.2.0.jar                        |Road Stuff                    |roadstuff                     |1.16.4-4.2.0        |DONE      |NOSIGNATURE
		ImmersiveRailroading-1.16.4-forge-1.8.0.1.jar     |Immersive Railroading         |immersiverailroading          |1.16.4-forge-1.8.0  |DONE      |NOSIGNATURE
		engineersdecor-1.16.4-1.1.4.jar                   |Engineer's Decor              |engineersdecor                |1.1.4               |DONE      |bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		forge-1.16.4-35.1.10-universal.jar                |Forge                         |forge                         |35.1.10             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		VendingMachine-1.16.2-1.0.0.3.jar                 |Vending Machine               |vm                            |1.0.0.3             |DONE      |NOSIGNATURE
		refinedstorage-1.9.9.jar                          |Refined Storage               |refinedstorage                |1.9.9               |DONE      |NOSIGNATURE
		PrettyPipes-1.9.0.jar                             |Pretty Pipes                  |prettypipes                   |1.9.0               |DONE      |NOSIGNATURE
		UniversalModCore-1.16.4-forge-1.0.0-fixed.jar     |Universal Mod Core            |universalmodcore              |1.0.0               |DONE      |NOSIGNATURE
	Crash Report UUID: 8dc18e4b-e118-496c-87d1-6d30a1daaf43
	Launched Version: 1.16.4-forge-35.1.10
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: NVIDIA GeForce GT 650M OpenGL Engine GL version 2.1 NVIDIA-14.0.32 355.11.11.10.10.143, NVIDIA Corporation
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	GPU Warnings: version: 2.1
	Graphics mode: fast
	Resource Packs: vanilla, mod_resources
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz

**Comment by ChAoSUnItY** [comment]
The Exception is clear, but I'm wondering how this happened? Can you describe the procedure?

**Comment by Scwestbrook** [comment]
Sure! I was in my station and was going out backwards, when suddenly, right before I looked at the sign, it froze, and in about 2 minutes it crashed.
It also said this:
Error code 255:
Game crashed whilst rendering block entity

**Comment by ChAoSUnItY** [comment]
Did your station delete before you l try to look at the sign?

**Comment by Scwestbrook** [comment]
No
